import { Toaster } from "@/components/ui/toaster";
import "./globals.css";
import type { Metadata } from "next";
import { Work_Sans } from "next/font/google";
import AuthSessionProvider from "@/components/providers/SessionProvider";
import ReactQueryProvider from "@/components/providers/ReactQueryProvider";



const inter = Work_Sans({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthSessionProvider>
          <ReactQueryProvider>
            <Toaster />
            {children}
          </ReactQueryProvider>
        </AuthSessionProvider>
      </body>
    </html>
  );
}
